name: main
on: workflow_dispatch

jobs:
  CD:
    runs-on: macos-latest

    steps:
      - name: Set up checkout
        uses: actions/checkout@v3

      - name: Set up Yarn cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-modules-cache-

      - name: Set up Electron cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.cache/electron
          key: ${{ runner.os }}-electron-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-electron-cache-

      - name: Set up Electron Builder cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.cache/electron-builder
          key: ${{ runner.os }}-electron-builder-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-electron-builder-cache-

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Set up dependencies
        run: yarn --ignore-scripts

      - name: Lint
        run: yarn lint

      - name: Create .env file
        run: |
          touch .env
          echo VUE_APP_ELECTRON_STORE_KEY=${{ secrets.ELECTRON_STORE_KEY }} >> .env
          echo VUE_APP_ANONYMOUS_TOKEN=${{ secrets.ANONYMOUS_TOKEN }} >> .env
          cat .env

      - name: Release
        env:
          ELECTRON_CACHE: ${{ github.workspace }}/.cache/electron
          ELECTRON_BUILDER_CACHE: ${{ github.workspace }}/.cache/electron-builder
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: yarn release

      - name: Clear Wine cache
        run: rm -rf ${{ github.workspace }}/.cache/electron-builder/wine
